# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
