# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20160918_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='episode',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='season',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
